// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	fcdclient "github.com/smartcontractkit/chainlink-cosmos/pkg/monitoring/fcdclient"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetBlockAtHeight provides a mock function with given fields: _a0, _a1
func (_m *Client) GetBlockAtHeight(_a0 context.Context, _a1 uint64) (fcdclient.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockAtHeight")
	}

	var r0 fcdclient.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (fcdclient.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) fcdclient.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(fcdclient.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetBlockAtHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockAtHeight'
type Client_GetBlockAtHeight_Call struct {
	*mock.Call
}

// GetBlockAtHeight is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
func (_e *Client_Expecter) GetBlockAtHeight(_a0 interface{}, _a1 interface{}) *Client_GetBlockAtHeight_Call {
	return &Client_GetBlockAtHeight_Call{Call: _e.mock.On("GetBlockAtHeight", _a0, _a1)}
}

func (_c *Client_GetBlockAtHeight_Call) Run(run func(_a0 context.Context, _a1 uint64)) *Client_GetBlockAtHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Client_GetBlockAtHeight_Call) Return(_a0 fcdclient.Response, _a1 error) *Client_GetBlockAtHeight_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetBlockAtHeight_Call) RunAndReturn(run func(context.Context, uint64) (fcdclient.Response, error)) *Client_GetBlockAtHeight_Call {
	_c.Call.Return(run)
	return _c
}

// GetTxList provides a mock function with given fields: _a0, _a1
func (_m *Client) GetTxList(_a0 context.Context, _a1 fcdclient.GetTxListParams) (fcdclient.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetTxList")
	}

	var r0 fcdclient.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, fcdclient.GetTxListParams) (fcdclient.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, fcdclient.GetTxListParams) fcdclient.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(fcdclient.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, fcdclient.GetTxListParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTxList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTxList'
type Client_GetTxList_Call struct {
	*mock.Call
}

// GetTxList is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 fcdclient.GetTxListParams
func (_e *Client_Expecter) GetTxList(_a0 interface{}, _a1 interface{}) *Client_GetTxList_Call {
	return &Client_GetTxList_Call{Call: _e.mock.On("GetTxList", _a0, _a1)}
}

func (_c *Client_GetTxList_Call) Run(run func(_a0 context.Context, _a1 fcdclient.GetTxListParams)) *Client_GetTxList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(fcdclient.GetTxListParams))
	})
	return _c
}

func (_c *Client_GetTxList_Call) Return(_a0 fcdclient.Response, _a1 error) *Client_GetTxList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTxList_Call) RunAndReturn(run func(context.Context, fcdclient.GetTxListParams) (fcdclient.Response, error)) *Client_GetTxList_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
