name: Build Contract Artifacts
description: Common builder for contract artifacts

runs:
  using: composite
  steps:
    - name: Cache cargo registry
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-v2-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-v2-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Build Contracts
      shell: bash
      run: make contracts_compile
    - name: Upload Contract Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
