[[Cosmos]]
Enabled = true
ChainID = 'testing'
[[Cosmos.Nodes]]
Name = 'primary'
TendermintURL = 'http://tendermint-rpc:26657'

[OCR2]
Enabled = true

[P2P]
[P2P.V1]
Enabled = false
[P2P.V2]
Enabled = true
DeltaDial = '5s'
DeltaReconcile = '5s'
ListenAddresses = ['0.0.0.0:6690']

[Webserver]
[Webserver.TLS]
HTTPSPort = 0
