// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	cmtservice "github.com/cosmos/cosmos-sdk/client/grpc/cmtservice"
	client "github.com/smartcontractkit/chainlink-cosmos/pkg/cosmos/client"

	context "context"

	cosmos_sdkclient "github.com/cosmos/cosmos-sdk/client"

	cryptotypes "github.com/cosmos/cosmos-sdk/crypto/types"

	mock "github.com/stretchr/testify/mock"

	query "github.com/cosmos/cosmos-sdk/types/query"

	tx "github.com/cosmos/cosmos-sdk/types/tx"

	types "github.com/cosmos/cosmos-sdk/types"
)

// ReaderWriter is an autogenerated mock type for the ReaderWriter type
type ReaderWriter struct {
	mock.Mock
}

type ReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *ReaderWriter) EXPECT() *ReaderWriter_Expecter {
	return &ReaderWriter_Expecter{mock: &_m.Mock}
}

// Account provides a mock function with given fields: ctx, address
func (_m *ReaderWriter) Account(ctx context.Context, address types.AccAddress) (uint64, uint64, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Account")
	}

	var r0 uint64
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress) (uint64, uint64, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress) uint64); ok {
		r0 = rf(ctx, address)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AccAddress) uint64); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, types.AccAddress) error); ok {
		r2 = rf(ctx, address)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReaderWriter_Account_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Account'
type ReaderWriter_Account_Call struct {
	*mock.Call
}

// Account is a helper method to define mock.On call
//   - ctx context.Context
//   - address types.AccAddress
func (_e *ReaderWriter_Expecter) Account(ctx interface{}, address interface{}) *ReaderWriter_Account_Call {
	return &ReaderWriter_Account_Call{Call: _e.mock.On("Account", ctx, address)}
}

func (_c *ReaderWriter_Account_Call) Run(run func(ctx context.Context, address types.AccAddress)) *ReaderWriter_Account_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AccAddress))
	})
	return _c
}

func (_c *ReaderWriter_Account_Call) Return(_a0 uint64, _a1 uint64, _a2 error) *ReaderWriter_Account_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ReaderWriter_Account_Call) RunAndReturn(run func(context.Context, types.AccAddress) (uint64, uint64, error)) *ReaderWriter_Account_Call {
	_c.Call.Return(run)
	return _c
}

// Balance provides a mock function with given fields: ctx, addr, denom
func (_m *ReaderWriter) Balance(ctx context.Context, addr types.AccAddress, denom string) (*types.Coin, error) {
	ret := _m.Called(ctx, addr, denom)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 *types.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, string) (*types.Coin, error)); ok {
		return rf(ctx, addr, denom)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, string) *types.Coin); ok {
		r0 = rf(ctx, addr, denom)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AccAddress, string) error); ok {
		r1 = rf(ctx, addr, denom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type ReaderWriter_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - ctx context.Context
//   - addr types.AccAddress
//   - denom string
func (_e *ReaderWriter_Expecter) Balance(ctx interface{}, addr interface{}, denom interface{}) *ReaderWriter_Balance_Call {
	return &ReaderWriter_Balance_Call{Call: _e.mock.On("Balance", ctx, addr, denom)}
}

func (_c *ReaderWriter_Balance_Call) Run(run func(ctx context.Context, addr types.AccAddress, denom string)) *ReaderWriter_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AccAddress), args[2].(string))
	})
	return _c
}

func (_c *ReaderWriter_Balance_Call) Return(_a0 *types.Coin, _a1 error) *ReaderWriter_Balance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_Balance_Call) RunAndReturn(run func(context.Context, types.AccAddress, string) (*types.Coin, error)) *ReaderWriter_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// BatchSimulateUnsigned provides a mock function with given fields: ctx, msgs, sequence
func (_m *ReaderWriter) BatchSimulateUnsigned(ctx context.Context, msgs client.SimMsgs, sequence uint64) (*client.BatchSimResults, error) {
	ret := _m.Called(ctx, msgs, sequence)

	if len(ret) == 0 {
		panic("no return value specified for BatchSimulateUnsigned")
	}

	var r0 *client.BatchSimResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.SimMsgs, uint64) (*client.BatchSimResults, error)); ok {
		return rf(ctx, msgs, sequence)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.SimMsgs, uint64) *client.BatchSimResults); ok {
		r0 = rf(ctx, msgs, sequence)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.BatchSimResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.SimMsgs, uint64) error); ok {
		r1 = rf(ctx, msgs, sequence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_BatchSimulateUnsigned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchSimulateUnsigned'
type ReaderWriter_BatchSimulateUnsigned_Call struct {
	*mock.Call
}

// BatchSimulateUnsigned is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs client.SimMsgs
//   - sequence uint64
func (_e *ReaderWriter_Expecter) BatchSimulateUnsigned(ctx interface{}, msgs interface{}, sequence interface{}) *ReaderWriter_BatchSimulateUnsigned_Call {
	return &ReaderWriter_BatchSimulateUnsigned_Call{Call: _e.mock.On("BatchSimulateUnsigned", ctx, msgs, sequence)}
}

func (_c *ReaderWriter_BatchSimulateUnsigned_Call) Run(run func(ctx context.Context, msgs client.SimMsgs, sequence uint64)) *ReaderWriter_BatchSimulateUnsigned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.SimMsgs), args[2].(uint64))
	})
	return _c
}

func (_c *ReaderWriter_BatchSimulateUnsigned_Call) Return(_a0 *client.BatchSimResults, _a1 error) *ReaderWriter_BatchSimulateUnsigned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_BatchSimulateUnsigned_Call) RunAndReturn(run func(context.Context, client.SimMsgs, uint64) (*client.BatchSimResults, error)) *ReaderWriter_BatchSimulateUnsigned_Call {
	_c.Call.Return(run)
	return _c
}

// BlockByHeight provides a mock function with given fields: ctx, height
func (_m *ReaderWriter) BlockByHeight(ctx context.Context, height int64) (*cmtservice.GetBlockByHeightResponse, error) {
	ret := _m.Called(ctx, height)

	if len(ret) == 0 {
		panic("no return value specified for BlockByHeight")
	}

	var r0 *cmtservice.GetBlockByHeightResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*cmtservice.GetBlockByHeightResponse, error)); ok {
		return rf(ctx, height)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *cmtservice.GetBlockByHeightResponse); ok {
		r0 = rf(ctx, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cmtservice.GetBlockByHeightResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_BlockByHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockByHeight'
type ReaderWriter_BlockByHeight_Call struct {
	*mock.Call
}

// BlockByHeight is a helper method to define mock.On call
//   - ctx context.Context
//   - height int64
func (_e *ReaderWriter_Expecter) BlockByHeight(ctx interface{}, height interface{}) *ReaderWriter_BlockByHeight_Call {
	return &ReaderWriter_BlockByHeight_Call{Call: _e.mock.On("BlockByHeight", ctx, height)}
}

func (_c *ReaderWriter_BlockByHeight_Call) Run(run func(ctx context.Context, height int64)) *ReaderWriter_BlockByHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ReaderWriter_BlockByHeight_Call) Return(_a0 *cmtservice.GetBlockByHeightResponse, _a1 error) *ReaderWriter_BlockByHeight_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_BlockByHeight_Call) RunAndReturn(run func(context.Context, int64) (*cmtservice.GetBlockByHeightResponse, error)) *ReaderWriter_BlockByHeight_Call {
	_c.Call.Return(run)
	return _c
}

// Broadcast provides a mock function with given fields: ctx, txBytes, mode
func (_m *ReaderWriter) Broadcast(ctx context.Context, txBytes []byte, mode tx.BroadcastMode) (*tx.BroadcastTxResponse, error) {
	ret := _m.Called(ctx, txBytes, mode)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 *tx.BroadcastTxResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, tx.BroadcastMode) (*tx.BroadcastTxResponse, error)); ok {
		return rf(ctx, txBytes, mode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, tx.BroadcastMode) *tx.BroadcastTxResponse); ok {
		r0 = rf(ctx, txBytes, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx.BroadcastTxResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, tx.BroadcastMode) error); ok {
		r1 = rf(ctx, txBytes, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type ReaderWriter_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - txBytes []byte
//   - mode tx.BroadcastMode
func (_e *ReaderWriter_Expecter) Broadcast(ctx interface{}, txBytes interface{}, mode interface{}) *ReaderWriter_Broadcast_Call {
	return &ReaderWriter_Broadcast_Call{Call: _e.mock.On("Broadcast", ctx, txBytes, mode)}
}

func (_c *ReaderWriter_Broadcast_Call) Run(run func(ctx context.Context, txBytes []byte, mode tx.BroadcastMode)) *ReaderWriter_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(tx.BroadcastMode))
	})
	return _c
}

func (_c *ReaderWriter_Broadcast_Call) Return(_a0 *tx.BroadcastTxResponse, _a1 error) *ReaderWriter_Broadcast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_Broadcast_Call) RunAndReturn(run func(context.Context, []byte, tx.BroadcastMode) (*tx.BroadcastTxResponse, error)) *ReaderWriter_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with no fields
func (_m *ReaderWriter) Context() *cosmos_sdkclient.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 *cosmos_sdkclient.Context
	if rf, ok := ret.Get(0).(func() *cosmos_sdkclient.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cosmos_sdkclient.Context)
		}
	}

	return r0
}

// ReaderWriter_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type ReaderWriter_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *ReaderWriter_Expecter) Context() *ReaderWriter_Context_Call {
	return &ReaderWriter_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *ReaderWriter_Context_Call) Run(run func()) *ReaderWriter_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReaderWriter_Context_Call) Return(_a0 *cosmos_sdkclient.Context) *ReaderWriter_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReaderWriter_Context_Call) RunAndReturn(run func() *cosmos_sdkclient.Context) *ReaderWriter_Context_Call {
	_c.Call.Return(run)
	return _c
}

// ContractState provides a mock function with given fields: ctx, contractAddress, queryMsg
func (_m *ReaderWriter) ContractState(ctx context.Context, contractAddress types.AccAddress, queryMsg []byte) ([]byte, error) {
	ret := _m.Called(ctx, contractAddress, queryMsg)

	if len(ret) == 0 {
		panic("no return value specified for ContractState")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, []byte) ([]byte, error)); ok {
		return rf(ctx, contractAddress, queryMsg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, []byte) []byte); ok {
		r0 = rf(ctx, contractAddress, queryMsg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AccAddress, []byte) error); ok {
		r1 = rf(ctx, contractAddress, queryMsg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_ContractState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractState'
type ReaderWriter_ContractState_Call struct {
	*mock.Call
}

// ContractState is a helper method to define mock.On call
//   - ctx context.Context
//   - contractAddress types.AccAddress
//   - queryMsg []byte
func (_e *ReaderWriter_Expecter) ContractState(ctx interface{}, contractAddress interface{}, queryMsg interface{}) *ReaderWriter_ContractState_Call {
	return &ReaderWriter_ContractState_Call{Call: _e.mock.On("ContractState", ctx, contractAddress, queryMsg)}
}

func (_c *ReaderWriter_ContractState_Call) Run(run func(ctx context.Context, contractAddress types.AccAddress, queryMsg []byte)) *ReaderWriter_ContractState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AccAddress), args[2].([]byte))
	})
	return _c
}

func (_c *ReaderWriter_ContractState_Call) Return(_a0 []byte, _a1 error) *ReaderWriter_ContractState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_ContractState_Call) RunAndReturn(run func(context.Context, types.AccAddress, []byte) ([]byte, error)) *ReaderWriter_ContractState_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAndSign provides a mock function with given fields: ctx, msgs, account, sequence, gasLimit, gasLimitMultiplier, gasPrice, signer, timeoutHeight
func (_m *ReaderWriter) CreateAndSign(ctx context.Context, msgs []types.Msg, account uint64, sequence uint64, gasLimit uint64, gasLimitMultiplier float64, gasPrice types.DecCoin, signer cryptotypes.PrivKey, timeoutHeight uint64) ([]byte, error) {
	ret := _m.Called(ctx, msgs, account, sequence, gasLimit, gasLimitMultiplier, gasPrice, signer, timeoutHeight)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndSign")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.Msg, uint64, uint64, uint64, float64, types.DecCoin, cryptotypes.PrivKey, uint64) ([]byte, error)); ok {
		return rf(ctx, msgs, account, sequence, gasLimit, gasLimitMultiplier, gasPrice, signer, timeoutHeight)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.Msg, uint64, uint64, uint64, float64, types.DecCoin, cryptotypes.PrivKey, uint64) []byte); ok {
		r0 = rf(ctx, msgs, account, sequence, gasLimit, gasLimitMultiplier, gasPrice, signer, timeoutHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.Msg, uint64, uint64, uint64, float64, types.DecCoin, cryptotypes.PrivKey, uint64) error); ok {
		r1 = rf(ctx, msgs, account, sequence, gasLimit, gasLimitMultiplier, gasPrice, signer, timeoutHeight)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_CreateAndSign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAndSign'
type ReaderWriter_CreateAndSign_Call struct {
	*mock.Call
}

// CreateAndSign is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []types.Msg
//   - account uint64
//   - sequence uint64
//   - gasLimit uint64
//   - gasLimitMultiplier float64
//   - gasPrice types.DecCoin
//   - signer cryptotypes.PrivKey
//   - timeoutHeight uint64
func (_e *ReaderWriter_Expecter) CreateAndSign(ctx interface{}, msgs interface{}, account interface{}, sequence interface{}, gasLimit interface{}, gasLimitMultiplier interface{}, gasPrice interface{}, signer interface{}, timeoutHeight interface{}) *ReaderWriter_CreateAndSign_Call {
	return &ReaderWriter_CreateAndSign_Call{Call: _e.mock.On("CreateAndSign", ctx, msgs, account, sequence, gasLimit, gasLimitMultiplier, gasPrice, signer, timeoutHeight)}
}

func (_c *ReaderWriter_CreateAndSign_Call) Run(run func(ctx context.Context, msgs []types.Msg, account uint64, sequence uint64, gasLimit uint64, gasLimitMultiplier float64, gasPrice types.DecCoin, signer cryptotypes.PrivKey, timeoutHeight uint64)) *ReaderWriter_CreateAndSign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.Msg), args[2].(uint64), args[3].(uint64), args[4].(uint64), args[5].(float64), args[6].(types.DecCoin), args[7].(cryptotypes.PrivKey), args[8].(uint64))
	})
	return _c
}

func (_c *ReaderWriter_CreateAndSign_Call) Return(_a0 []byte, _a1 error) *ReaderWriter_CreateAndSign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_CreateAndSign_Call) RunAndReturn(run func(context.Context, []types.Msg, uint64, uint64, uint64, float64, types.DecCoin, cryptotypes.PrivKey, uint64) ([]byte, error)) *ReaderWriter_CreateAndSign_Call {
	_c.Call.Return(run)
	return _c
}

// LatestBlock provides a mock function with given fields: _a0
func (_m *ReaderWriter) LatestBlock(_a0 context.Context) (*cmtservice.GetLatestBlockResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LatestBlock")
	}

	var r0 *cmtservice.GetLatestBlockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*cmtservice.GetLatestBlockResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *cmtservice.GetLatestBlockResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cmtservice.GetLatestBlockResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_LatestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestBlock'
type ReaderWriter_LatestBlock_Call struct {
	*mock.Call
}

// LatestBlock is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ReaderWriter_Expecter) LatestBlock(_a0 interface{}) *ReaderWriter_LatestBlock_Call {
	return &ReaderWriter_LatestBlock_Call{Call: _e.mock.On("LatestBlock", _a0)}
}

func (_c *ReaderWriter_LatestBlock_Call) Run(run func(_a0 context.Context)) *ReaderWriter_LatestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReaderWriter_LatestBlock_Call) Return(_a0 *cmtservice.GetLatestBlockResponse, _a1 error) *ReaderWriter_LatestBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_LatestBlock_Call) RunAndReturn(run func(context.Context) (*cmtservice.GetLatestBlockResponse, error)) *ReaderWriter_LatestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SignAndBroadcast provides a mock function with given fields: ctx, msgs, accountNum, sequence, gasPrice, signer, mode
func (_m *ReaderWriter) SignAndBroadcast(ctx context.Context, msgs []types.Msg, accountNum uint64, sequence uint64, gasPrice types.DecCoin, signer cryptotypes.PrivKey, mode tx.BroadcastMode) (*tx.BroadcastTxResponse, error) {
	ret := _m.Called(ctx, msgs, accountNum, sequence, gasPrice, signer, mode)

	if len(ret) == 0 {
		panic("no return value specified for SignAndBroadcast")
	}

	var r0 *tx.BroadcastTxResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.Msg, uint64, uint64, types.DecCoin, cryptotypes.PrivKey, tx.BroadcastMode) (*tx.BroadcastTxResponse, error)); ok {
		return rf(ctx, msgs, accountNum, sequence, gasPrice, signer, mode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.Msg, uint64, uint64, types.DecCoin, cryptotypes.PrivKey, tx.BroadcastMode) *tx.BroadcastTxResponse); ok {
		r0 = rf(ctx, msgs, accountNum, sequence, gasPrice, signer, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx.BroadcastTxResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.Msg, uint64, uint64, types.DecCoin, cryptotypes.PrivKey, tx.BroadcastMode) error); ok {
		r1 = rf(ctx, msgs, accountNum, sequence, gasPrice, signer, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_SignAndBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignAndBroadcast'
type ReaderWriter_SignAndBroadcast_Call struct {
	*mock.Call
}

// SignAndBroadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []types.Msg
//   - accountNum uint64
//   - sequence uint64
//   - gasPrice types.DecCoin
//   - signer cryptotypes.PrivKey
//   - mode tx.BroadcastMode
func (_e *ReaderWriter_Expecter) SignAndBroadcast(ctx interface{}, msgs interface{}, accountNum interface{}, sequence interface{}, gasPrice interface{}, signer interface{}, mode interface{}) *ReaderWriter_SignAndBroadcast_Call {
	return &ReaderWriter_SignAndBroadcast_Call{Call: _e.mock.On("SignAndBroadcast", ctx, msgs, accountNum, sequence, gasPrice, signer, mode)}
}

func (_c *ReaderWriter_SignAndBroadcast_Call) Run(run func(ctx context.Context, msgs []types.Msg, accountNum uint64, sequence uint64, gasPrice types.DecCoin, signer cryptotypes.PrivKey, mode tx.BroadcastMode)) *ReaderWriter_SignAndBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.Msg), args[2].(uint64), args[3].(uint64), args[4].(types.DecCoin), args[5].(cryptotypes.PrivKey), args[6].(tx.BroadcastMode))
	})
	return _c
}

func (_c *ReaderWriter_SignAndBroadcast_Call) Return(_a0 *tx.BroadcastTxResponse, _a1 error) *ReaderWriter_SignAndBroadcast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_SignAndBroadcast_Call) RunAndReturn(run func(context.Context, []types.Msg, uint64, uint64, types.DecCoin, cryptotypes.PrivKey, tx.BroadcastMode) (*tx.BroadcastTxResponse, error)) *ReaderWriter_SignAndBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// Simulate provides a mock function with given fields: ctx, txBytes
func (_m *ReaderWriter) Simulate(ctx context.Context, txBytes []byte) (*tx.SimulateResponse, error) {
	ret := _m.Called(ctx, txBytes)

	if len(ret) == 0 {
		panic("no return value specified for Simulate")
	}

	var r0 *tx.SimulateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (*tx.SimulateResponse, error)); ok {
		return rf(ctx, txBytes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *tx.SimulateResponse); ok {
		r0 = rf(ctx, txBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx.SimulateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, txBytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_Simulate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Simulate'
type ReaderWriter_Simulate_Call struct {
	*mock.Call
}

// Simulate is a helper method to define mock.On call
//   - ctx context.Context
//   - txBytes []byte
func (_e *ReaderWriter_Expecter) Simulate(ctx interface{}, txBytes interface{}) *ReaderWriter_Simulate_Call {
	return &ReaderWriter_Simulate_Call{Call: _e.mock.On("Simulate", ctx, txBytes)}
}

func (_c *ReaderWriter_Simulate_Call) Run(run func(ctx context.Context, txBytes []byte)) *ReaderWriter_Simulate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *ReaderWriter_Simulate_Call) Return(_a0 *tx.SimulateResponse, _a1 error) *ReaderWriter_Simulate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_Simulate_Call) RunAndReturn(run func(context.Context, []byte) (*tx.SimulateResponse, error)) *ReaderWriter_Simulate_Call {
	_c.Call.Return(run)
	return _c
}

// SimulateUnsigned provides a mock function with given fields: ctx, msgs, sequence
func (_m *ReaderWriter) SimulateUnsigned(ctx context.Context, msgs []types.Msg, sequence uint64) (*tx.SimulateResponse, error) {
	ret := _m.Called(ctx, msgs, sequence)

	if len(ret) == 0 {
		panic("no return value specified for SimulateUnsigned")
	}

	var r0 *tx.SimulateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.Msg, uint64) (*tx.SimulateResponse, error)); ok {
		return rf(ctx, msgs, sequence)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.Msg, uint64) *tx.SimulateResponse); ok {
		r0 = rf(ctx, msgs, sequence)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx.SimulateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.Msg, uint64) error); ok {
		r1 = rf(ctx, msgs, sequence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_SimulateUnsigned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulateUnsigned'
type ReaderWriter_SimulateUnsigned_Call struct {
	*mock.Call
}

// SimulateUnsigned is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []types.Msg
//   - sequence uint64
func (_e *ReaderWriter_Expecter) SimulateUnsigned(ctx interface{}, msgs interface{}, sequence interface{}) *ReaderWriter_SimulateUnsigned_Call {
	return &ReaderWriter_SimulateUnsigned_Call{Call: _e.mock.On("SimulateUnsigned", ctx, msgs, sequence)}
}

func (_c *ReaderWriter_SimulateUnsigned_Call) Run(run func(ctx context.Context, msgs []types.Msg, sequence uint64)) *ReaderWriter_SimulateUnsigned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.Msg), args[2].(uint64))
	})
	return _c
}

func (_c *ReaderWriter_SimulateUnsigned_Call) Return(_a0 *tx.SimulateResponse, _a1 error) *ReaderWriter_SimulateUnsigned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_SimulateUnsigned_Call) RunAndReturn(run func(context.Context, []types.Msg, uint64) (*tx.SimulateResponse, error)) *ReaderWriter_SimulateUnsigned_Call {
	_c.Call.Return(run)
	return _c
}

// Tx provides a mock function with given fields: ctx, hash
func (_m *ReaderWriter) Tx(ctx context.Context, hash string) (*tx.GetTxResponse, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for Tx")
	}

	var r0 *tx.GetTxResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*tx.GetTxResponse, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *tx.GetTxResponse); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx.GetTxResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_Tx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tx'
type ReaderWriter_Tx_Call struct {
	*mock.Call
}

// Tx is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *ReaderWriter_Expecter) Tx(ctx interface{}, hash interface{}) *ReaderWriter_Tx_Call {
	return &ReaderWriter_Tx_Call{Call: _e.mock.On("Tx", ctx, hash)}
}

func (_c *ReaderWriter_Tx_Call) Run(run func(ctx context.Context, hash string)) *ReaderWriter_Tx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReaderWriter_Tx_Call) Return(_a0 *tx.GetTxResponse, _a1 error) *ReaderWriter_Tx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_Tx_Call) RunAndReturn(run func(context.Context, string) (*tx.GetTxResponse, error)) *ReaderWriter_Tx_Call {
	_c.Call.Return(run)
	return _c
}

// TxsEvents provides a mock function with given fields: ctx, events, paginationParams
func (_m *ReaderWriter) TxsEvents(ctx context.Context, events []string, paginationParams *query.PageRequest) (*tx.GetTxsEventResponse, error) {
	ret := _m.Called(ctx, events, paginationParams)

	if len(ret) == 0 {
		panic("no return value specified for TxsEvents")
	}

	var r0 *tx.GetTxsEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, *query.PageRequest) (*tx.GetTxsEventResponse, error)); ok {
		return rf(ctx, events, paginationParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, *query.PageRequest) *tx.GetTxsEventResponse); ok {
		r0 = rf(ctx, events, paginationParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tx.GetTxsEventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, *query.PageRequest) error); ok {
		r1 = rf(ctx, events, paginationParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderWriter_TxsEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxsEvents'
type ReaderWriter_TxsEvents_Call struct {
	*mock.Call
}

// TxsEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - events []string
//   - paginationParams *query.PageRequest
func (_e *ReaderWriter_Expecter) TxsEvents(ctx interface{}, events interface{}, paginationParams interface{}) *ReaderWriter_TxsEvents_Call {
	return &ReaderWriter_TxsEvents_Call{Call: _e.mock.On("TxsEvents", ctx, events, paginationParams)}
}

func (_c *ReaderWriter_TxsEvents_Call) Run(run func(ctx context.Context, events []string, paginationParams *query.PageRequest)) *ReaderWriter_TxsEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(*query.PageRequest))
	})
	return _c
}

func (_c *ReaderWriter_TxsEvents_Call) Return(_a0 *tx.GetTxsEventResponse, _a1 error) *ReaderWriter_TxsEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderWriter_TxsEvents_Call) RunAndReturn(run func(context.Context, []string, *query.PageRequest) (*tx.GetTxsEventResponse, error)) *ReaderWriter_TxsEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewReaderWriter creates a new instance of ReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReaderWriter {
	mock := &ReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
