name: e2e_chaos_tests
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
    inputs:
      cl_branch_ref:
        description: Chainlink repo branch to integrate with
        required: true
        default: develop
        type: string

jobs:
  e2e_chaos_build_custom_chainlink_image:
    name: E2E Chaos Build Custom CL Image
    # target branch can't be set as var, it's from where we getting pipeline code
    uses: smartcontractkit/chainlink/.github/workflows/build-custom.yml@develop
    with:
      cl_repo: smartcontractkit/chainlink
      # by default we are integrating with develop
      cl_ref: ${{ github.event.inputs.cl_branch_ref }}
      # commit of the caller branch
      dep_terra_sha: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.QA_AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
      QA_PRIVATE_GHA_PULL: "false"
  e2e_chaos_build_contracts:
    name: E2E Chaos Build Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Build Test Artifacts
        uses: ./.github/actions/build_test_artifacts
  e2e_run_chaos_tests:
    name: E2E Run Chaos Tests
    runs-on: ubuntu-latest
    needs: [e2e_chaos_build_contracts, e2e_chaos_build_custom_chainlink_image]
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Run Tests
        uses: smartcontractkit/ctf-ci-e2e-action@v1.0.0
        with:
          test_command_to_run: make test_chaos
          cl_repo: 795953128386.dkr.ecr.us-west-2.amazonaws.com/chainlink
          cl_image_tag: custom.${{ github.sha }}
          download_artifacts_path: artifacts
          publish_report_paths: "./tests-chaos-report.xml"
          publish_check_name: Chaos Test Results
          QA_AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          QA_AWS_SECRET_KEY: ${{ secrets.QA_AWS_SECRET_KEY }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: "1"
