name: E2E Chaos Tests
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
    inputs:
      cl_branch_ref:
        description: Chainlink repo branch to integrate with
        required: true
        default: develop
        type: string

jobs:
  E2E_Chaos_Build_Custom_Chainlink_Image:
    name: E2E Chaos Build Custom CL Image
    # target branch can't be set as var, it's from where we getting pipeline code
    uses: smartcontractkit/chainlink/.github/workflows/build-custom.yml@develop
    with:
      cl_repo: smartcontractkit/chainlink
      # by default we are integrating with develop
      cl_ref: ${{ github.event.inputs.cl_branch_ref }}
      # commit of the caller branch
      dep_terra_sha: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.QA_AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.QA_AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
  E2E_Chaos_Build_Contracts:
    name: E2E Chaos Build Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo registry
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-v2-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-v2-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Artifacts
        run: |
          make contracts_compile
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts
  E2E_Run_Chaos_Tests:
    name: E2E Run Chaos Tests
    runs-on: ubuntu-latest
    needs: [E2E_Chaos_Build_Contracts, E2E_Chaos_Build_Custom_Chainlink_Image]
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.QA_AWS_REGION }}
          role-to-assume: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.QA_KUBECONFIG }}
      - name: Cache Vendor Packages
        uses: actions/cache@v2
        id: cache-packages
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go Vendor Packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: go mod download
      - name: Install Ginkgo CLI
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.1.2
          go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.1.2
          go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.1.2
          go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: artifacts
          path: artifacts
      - name: Run Tests
        env:
          SELECTED_NETWORKS: localterra
          NETWORK_SETTINGS: /home/runner/work/chainlink-terra/chainlink-terra/tests/e2e/networks.yaml
          CHAINLINK_IMAGE: 795953128386.dkr.ecr.us-west-2.amazonaws.com/chainlink
          CHAINLINK_VERSION: custom.${{ github.sha }}
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          ginkgo tests/e2e/chaos
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "./tests-chaos-report.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Chaos Test Results
      - name: Publish Artifacts
        if: failure()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-logs
          path: /home/runner/work/chainlink-terra/chainlink-terra/tests/e2e/logs
