# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

on:
  push:
    branches:
      - develop
      - main
  pull_request:

name: contracts

jobs:

  contracts_unit_tests:
    name: Contract Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1

      - name: Install Nix
        uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "sandbox = false"

      # TODO: We probably want cachix enabled heres
      # https://github.com/smartcontractkit/chainlink-cosmos/issues/15

      - name: Run unit tests
        run: nix develop -c cargo unit-test --locked
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        run: nix develop -c cargo wasm --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

  contracts_lint:
    name: Contracts Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1

      - name: Install Nix
        uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "sandbox = false"

      - name: Avoid using non-nix rust binaries
        run: rm -rf ~/.cargo/bin

      - name: Run cargo fmt
        run: nix develop -c cargo fmt --all -- --check

      - name: Run cargo check
        run: nix develop -c cargo check

      - name: Run cargo clippy
        run: nix develop -c cargo clippy -- -D warnings

      # TODO: Add schema checks
      # https://github.com/smartcontractkit/chainlink-terra/issues/17
