name: gauntlet-release

on:
  push:
    tags:
      - "gauntlet-terra-contracts-v[0-9]+.[0-9]+.[0-9]" # i.e. gauntlet-terra-contracts-v1.0.0
      - "gauntlet-terra-contracts-v[0-9]+.[0-9]+.[0-9]+-rc*" # i.e. gauntlet-terra-contracts-v1.0.0-rc1
      - "gauntlet-terra-cw-plus-v[0-9]+.[0-9]+.[0-9]"
      - "gauntlet-terra-cw-plus-v[0-9]+.[0-9]+.[0-9]+-rc*"
      - "gauntlet-terra-v[0-9]+.[0-9]+.[0-9]"
      - "gauntlet-terra-v[0-9]+.[0-9]+.[0-9]+-rc*"

jobs:
  release-gauntlet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Set Env Variables
        run: echo "PKG_NAME=gauntlet-terra-contracts" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/gauntlet-terra-contracts-')
        run: echo "PKG_NAME=gauntlet-terra-cw-plus" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/gauntlet-terra-cw-plus-')
        run: echo "PKG_NAME=gauntlet-terra" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/gauntlet-terra-')
      - name: Build Gauntlet
        run: yarn && yarn bundle
      - name: Create Archive
        run: tar cfvz ${{env.PKG_NAME}}.tar.gz packages-ts/${{env.PKG_NAME}}/**
      - name: Release Gauntlet
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{env.PKG_NAME}}.tar.gz
            bin/gauntlet-terra-*
