name: gauntlet

on:
  push:

jobs:
  gauntlet_build:
    name: Gauntlet Build
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Install Nix
        uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "sandbox = false"
      - run: nix develop -c yarn install --frozen-lockfile
      - run: nix develop -c yarn build

  gauntlet_format:
    name: Gauntlet Format
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Install Nix
        uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "sandbox = false"
      - run: nix develop -c yarn install --frozen-lockfile
      - run: nix develop -c yarn lint:format

  gauntlet_run_tests:
    name: Gauntlet Run Tests
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Install Nix
        uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "sandbox = false"
      - run: nix develop -c yarn install --frozen-lockfile
      - run: nix develop -c yarn test:ci
